name: video_gozle
description: Gozle Video App
publish_to: 'none'

version: 1.0.12

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # db
  shared_preferences: ^2.2.1
  flutter_secure_storage: ^8.0.0
  # api
  dio: ^5.3.3
  http: ^1.1.0

  # localization
  intl: ^0.18.1
  turkmen_localization_support: ^0.0.5
  # turkmen_localization_support:
  #   git:
  #         url: https://github.com/FreeManProg/turkmen_localization_support.git
  #         ref: master

  flutter_localization: ^0.1.10
  # di
  get_it: ^7.2.0
  # business logic
  flutter_bloc: ^8.1.2
  provider: ^6.0.5
  # helpers
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  # get: 
  # share_plus: ^7.2.1

  
  # design
  flutter_svg: ^2.0.7
  path_provider: ^2.0.15
  collection: ^1.17.2
  syncfusion_flutter_pdfviewer: ^22.2.12
  pull_to_refresh: ^2.0.0
  sliding_up_panel:
  # sliding_up_panel:
  #     git:
  #       url: https://github.com/akshathjain/sliding_up_panel.git
  #       ref: master
  
  # for cookie pars
  sweet_cookie_jar:
    git:
          url: https://github.com/FreeManProg/sweet-cookie-jar.git
          ref: main
  

  # other
  oauth2_client:
      git:
        url: https://github.com/FreeManProg/gozle_oauth2_client.git
        ref: main
        
  share_plus: ^7.2.1
  wakelock_plus: ^1.1.3
  url_launcher: ^6.1.14
  cached_network_image: ^3.3.0
  flutter_linkify: ^6.0.0
  dartz: ^0.10.1
  pretty_dio_logger: ^1.3.1

  

  flutter_hls_parser: ^2.0.1
  video_player: ^2.7.2
  double_tap_player_view: ^2.0.3
  flutter_animated_progress_bar: ^1.0.5
  flutter_cache_manager: ^3.3.1
  flutter_native_splash: ^2.3.8
  expandable_text: ^2.3.0

  firebase_in_app_messaging: ^0.7.4+8
  flutter_local_notifications: ^16.3.0
  firebase_messaging: ^14.7.9
  firebase_core: ^2.24.2
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1


  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.0
#  flutter_native_splash: ^2.3.2


flutter_icons:
  image_path_android: "assets/images/ic_logo.jpg"
  image_path_ios: "assets/images/ic_logo.jpg"
  android: true 
  ios: true 
  adaptive_icon_background: "assets/images/logo_background.png" 
  adaptive_icon_foreground: "assets/images/logo_foreground.png" 
  min_sdk_android: 21 
  remove_alpha_ios: true

#flutter_native_splash:
#
#  color: "#ffffff"
#  color_dark: "#ffffff"
#
#  image: assets/images/ic_logo.png
#  image_dark: assets/images/ic_logo.png
#
#  android_12:
#
#    image: assets/images/ic_logo.png
#    image_dark: assets/images/ic_logo.png
#
#    color: "#ffffff"
#    color_dark: "#ffffff"


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/menu/
    - assets/icons/player_icons/

    - assets/images/
    
    - assets/fonts/


  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/Geologica.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
flutter_intl:
  enabled: true
