name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.4'  # Укажите последнюю версию Flutter для канала stable

    - name: Build Flutter APK
      run: flutter build apk --debug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: build/app/outputs/flutter-apk/app-debug.apk
