name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.5.0'

    - name: Install Dependencies
      run: flutter pub get

    - name: Update Flutter and Dart
      run: flutter upgrade

    - name: Update Dart SDK
      run: flutter pub global activate dart

    - name: Install Dart SDK 3.0.0
      run: flutter pub global activate dart --channel=dev

    - name: Navigate to the App Directory
      run: cd gozle_video_app_flutter

    - name: Clean Flutter Cache and Get Dependencies
      run: |
        flutter clean
        flutter pub get

    - name: Build APK
      run: flutter build apk

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk
