name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'  # or specify your desired Flutter channel

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: build/app/outputs/flutter-apk/app-release.apk  # Update the path if needed

