name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Generate app-debug.apk
      run: |
        flutter build apk

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: build/app/outputs/flutter-apk/app-debug.apk
