name: Update Flutter, Dart, and Build APK

on:
  push:
    branches:
      - main

jobs:
  update-flutter-dart-and-build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update Flutter and Dart
      run: |
        cd $GITHUB_WORKSPACE/flutter
        git pull
        flutter_upgrade_result=$(flutter upgrade 2>&1) || echo $flutter_upgrade_result

    - name: Update Dart SDK
      run: flutter pub global activate dart

    - name: Install Dart SDK 3.0.0
      run: flutter pub global activate dart --channel=dev

    - name: Clean Flutter Cache and Get Dependencies
      run: |
        cd $GITHUB_WORKSPACE/gozle_video_app_flutter
        flutter clean
        flutter pub get

    - name: Build APK
      run: flutter build apk

    - name: Archive APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: gozle_video_app_flutter/build/app/outputs/flutter-apk/app-release.apk
