name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies and build
      run: |
        npm install  # или ваш способ установки зависимостей
        npm run build  # или ваш способ сборки проекта

    - name: Generate app-debug.apk
      run: |
        # Здесь вставьте команды для генерации вашего файла APK
        # Например, если вы используете Gradle:
        ./gradlew assembleDebug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: path/to/app/build/outputs/apk/debug/app-debug.apk  # Укажите правильный путь к вашему файлу APK
